### ISSUE TITLE
(Gem::Exception)

### ISSUE THREAD

**Issue by tsaohucn** [caius/bundler-native-gems#6] opened 2017-02-23 04:41 UTC
<pre>
/Users/kaogaau/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.3/lib/bundler/rubygems_integration.rb:407:in `block in replace_bin_path': can't find executable bundler-native-gems (Gem::Exception)
	from /Users/kaogaau/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.3/lib/bundler/rubygems_integration.rb:433:in `block in replace_bin_path'
	from /Users/kaogaau/.rvm/gems/ruby-2.3.3/bin/bundler-native-gems:22:in `<main>'
	from /Users/kaogaau/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/kaogaau/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
</pre>

My env :
rvm 1.27.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
Bundler version 1.14.3

Gemfile :
<pre>
source 'https://rubygems.org'

# Ruby 2.0 is the minimum requirement
ruby ['2.0.0', RUBY_VERSION].max

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end if Gem::Version.new(Bundler::VERSION) < Gem::Version.new('2')

# Load vendored dotenv gem and .env file
require File.join(File.dirname(__FILE__), 'lib/gemfile_helper.rb')
GemfileHelper.load_dotenv do |dotenv_dir|
  path dotenv_dir do
    gem 'dotenv'
    gem 'dotenv-rails'
  end
end

# Introduces a scope for gem loading based on a condition
def if_true(condition)
  if condition
    yield
  else
    # When not including the gems, we still want our Gemfile.lock
    # to include them, so we scope them to an unsupported platform.
    platform :ruby_18, &proc
  end
end

# Optional libraries.  To conserve RAM, comment out any that you don't need,
# then run `bundle` and commit the updated Gemfile and Gemfile.lock.
#gem 'twilio-ruby', '~> 3.11.5'    # TwilioAgent
#gem 'ruby-growl', '~> 4.1.0'      # GrowlAgent
#gem 'net-ftp-list', '~> 3.2.8'    # FtpsiteAgent
#gem 'wunderground', '~> 1.2.0'    # WeatherAgent
#gem 'forecast_io', '~> 2.0.0'     # WeatherAgent
#gem 'rturk', '~> 2.12.1'          # HumanTaskAgent
#gem 'hipchat', '~> 1.2.0'         # HipchatAgent
#gem 'xmpp4r',  '~> 0.5.6'         # JabberAgent
#gem 'mqtt'                        # MQTTAgent
#gem 'slack-notifier', '~> 1.0.0'  # SlackAgent
#gem 'hypdf', '~> 1.0.7'           # PDFInfoAgent

##Agents of Tomato
gem 'underscore-rails'
gem 'rest-client' # Restful API Client
gem 's3' # Amazon S3
gem 'base32' # Amazon S3
gem 'gcm' # NotificationAgent for anfroid
gem 'houston' # NotificationAgent fot ios
gem 'line-bot-api' # LinebotAgent
gem 'insnergy-api-ruby-client', '0.15.3' # InsnergyAgent
gem 'nhr-api-ruby-client', '0.6.0' # NhrAgent
gem 'google-api-client' # GoogleAgent
gem 'omniauth-dropbox-oauth2'
gem 'dropbox-api', github: 'unbox/dropbox-api', branch: 'oauth2-support' # DropboxAgent
gem 'koala' # FacebookAgent
gem 'evernote_oauth' # EvernoteAgent
gem 'pocket-ruby' # PocketAgent
gem 'ruby-trello', require: 'trello' # TrelloAgent
gem 'instagram', '>= 1.1.6' # InstagramAgent
gem 'viewpoint', github: 'WinRb/Viewpoint' # ExchangeAgent
gem 'lifx-http', require: 'lifx/http', github: 'tatey/lifx-http-client-ruby', ref: '274877b9e80a0ea5623898b915693e78484b072d' # LifxAgents
#gem 'ar-octopus'
# Bundler <1.5 does not recognize :x64_mingw as a valid platform name.
# Unfortunately, it can't self-update because it errors when encountering :x64_mingw.
unless Gem::Version.new(Bundler::VERSION) >= Gem::Version.new('1.5.0')
  STDERR.puts "Bundler >=1.5.0 is required.  Please upgrade bundler with 'gem install bundler'"
  exit 1
end
gem 'twitter', '~> 5.14.0' # Must to be loaded before cantino-twitter-stream. 
gem 'twitter-stream', github: 'cantino/twitter-stream', branch: 'huginn' 
gem 'omniauth-twitter'
gem 'protected_attributes', '~>1.0.8' # This must be loaded before some other gems, like delayed_job.
gem 'powder' # pow manager
gem 'ace-rails-ap', '~> 2.0.1'
gem 'bootstrap-kaminari-views', '~> 0.0.3'
gem 'bundler', '>= 1.5.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'daemons', '~> 1.1.9'
gem 'delayed_job', '~> 4.1.0'
gem 'delayed_job_active_record', github: 'collectiveidea/delayed_job_active_record', branch: 'master'
gem 'devise', '~> 3.5.4'
gem 'em-http-request', '~> 1.1.2'
gem 'faraday', '~> 0.9.0'
gem 'faraday_middleware'#, github: 'lostisland/faraday_middleware', branch: 'master'  # '>= 0.10.1'
gem 'feed-normalizer'
gem 'font-awesome-sass', '~> 4.3.2'
gem 'foreman', '~> 0.63.0'
gem 'premailer-rails'
# geokit-rails doesn't work with geokit 1.8.X but it specifies ~> 1.5
# in its own Gemfile.
gem 'geokit', '~> 1.8.4'
gem 'geokit-rails', '~> 2.0.1'
gem 'httparty', '~> 0.13'
gem 'jquery-rails', '~> 3.1.3'
gem 'json', '~> 1.8.1'
gem 'jsonpath', '~> 0.5.6'
gem 'kaminari', '~> 0.16.1'
gem 'kramdown', '~> 1.12.0'
gem 'liquid', '~> 3.0.3'
gem 'mini_magick'
gem 'multi_xml'
gem 'nokogiri', '1.6.7.2'
gem 'omniauth'
gem 'rails', '4.2.5.2'
gem 'rufus-scheduler', '~> 3.0.8', require: false
gem 'sass-rails',   '~> 5.0.3'
gem 'select2-rails', '~> 3.5.4'
gem 'spectrum-rails'
#gem 'string-scrub','0.1.1 '# for ruby <2.1
gem 'therubyracer', '~> 0.12.3'
gem 'typhoeus', '~> 0.6.3'
gem 'uglifier', '~> 2.7.2'
gem 'json-compare', '~> 0.1.8'
gem 'yajl-ruby'

group :development do
  gem 'reek'
  gem 'yaml_db'
  gem 'better_errors', '~> 1.1'
  gem 'binding_of_caller'
  gem 'quiet_assets'
  gem 'guard', '~> 2.13.0'
  gem 'guard-livereload', '~> 2.5.1'
  gem 'guard-rspec', '~> 4.6.4'
  gem 'rack-livereload', '~> 0.3.16'
  gem 'letter_opener_web'
  gem 'capistrano', '~> 3.4.0'
  gem 'capistrano-rails', '~> 1.1'
  gem 'capistrano-bundler', '~> 1.1.4'

  if_true(ENV['SPRING']) do
    gem 'spring-commands-rspec', '~> 1.0.4'
    gem 'spring', '~> 1.6.3'
  end

  group :test do
    gem 'coveralls', require: false
    gem 'delorean'
    gem 'poltergeist'
    gem 'capybara-select2', require: false
    gem 'pry-rails'
    gem 'rr'
    gem 'rspec', '~> 3.2'
    gem 'rspec-collection_matchers', '~> 1.1.0'
    gem 'rspec-rails', '~> 3.1'
    gem 'rspec-html-matchers', '~> 0.7'
    gem 'shoulda-matchers'
    gem 'vcr'
    gem 'webmock', '~> 1.17.4', require: false
    gem 'cucumber-rails', :require => false
    gem 'database_cleaner'
    gem "factory_girl_rails", "~> 4.0"
  end
end

group :production do
  gem 'rack', '> 1.5.0'
  gem 'unicorn', '~> 4.9.0'
end

# Platform requirements.
gem 'ffi', '>= 1.9.4'		# required by typhoeus; 1.9.4 has fixes for *BSD.
gem 'tzinfo', '>= 1.2.0'	# required by rails; 1.2.0 has support for *BSD and Solaris.
# Windows does not have zoneinfo files, so bundle the tzinfo-data gem.
#gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]

on_heroku = ENV['ON_HEROKU'] ||
            ENV['HEROKU_POSTGRESQL_ROSE_URL'] ||
            ENV['HEROKU_POSTGRESQL_GOLD_URL'] ||
            File.read(File.join(File.dirname(__FILE__), 'Procfile')) =~ /intended for Heroku/

ENV['DATABASE_ADAPTER'] ||=
  if on_heroku
    'postgresql'
  else
    'mysql2'
  end

if_true(on_heroku) do
  gem 'rails_12factor', group: :production
end

if_true(ENV['DATABASE_ADAPTER'].strip == 'postgresql') do
  gem 'pg', '~> 0.18.3'
end

if_true(ENV['DATABASE_ADAPTER'].strip == 'mysql2') do
  gem 'mysql2', '~> 0.3.20'
end

</pre>

**Comment by caius** [comment] 2024-08-30 12:51
This appears to be an issue finding the gem executable to run. I suspect perhaps RVM Gemsets getting in the way, given that was used in the environment.

Given the time since reporting (!) I'm going to close this as unreproducible now.

**Closed as completed by caius** 2024-08-30 12:51 UTC
